### ISSUE TITLE
Minimum angular speed not used for turns - only translational motion

### ISSUE THREAD

**Issue by iamthehazard** [purduesigbots/ARMS#110]
I'm not sure if this is intended, but currently minimum angular speed is only taken into consideration in `pid::translational()` Lines 127-130). It isn't used in `pid::angular()` at all - should it? Having this option (possibly as a separate config variable) would improve my turns considerably, especially wrt settling time.

**Comment by Jackman3323** [comment]
Minimum angular speed is there to prevent too much turning while translating (think fishtailing). If you want to put a max speed limit on your in-place turns, we have that functionality baked into the turn function (the optional "max" argument).
