### ISSUE TITLE
3 tracker odometry + IMU turning

### ISSUE THREAD

**Issue by Nightsoot** [purduesigbots/ARMS#92]
When trying to turn with 3 tracker odometry + IMU, the x and y values would drastically change and after a while would set to nan

**Comment by AndrewLuGit** [comment]
Hi, to make sure this is a code issue and not a configuration issue, would you mind providing some details about your odometry setup?
1. Starting from (0,0,0), does the x value increase when you move the robot forward and does the y value increase when you move the robot sideways to the left?
2. Are your left and right odometry wheels roughly equidistant from the center of the robot?
3. Is your middle odometry wheel in front of or behind the center of the robot?

**Comment by Nightsoot** [comment]
1.) yes
2.) yes
3.) yes

**Comment by AndrewLuGit** [comment]
I tested 3 wheel odometry + IMU on one of our robots yesterday and it worked fine. It might be something with your code. Can you link your repository? Also, to clarify my third point, the middle distance should be positive if it is behind the center of the robot, and negative if it is in front.

**Comment by Nightsoot** [comment]
I tested around with some variables and got it to work so the issue can be closed
